# Generated by Django 3.1.2 on 2020-10-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denguecase',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='denguecase',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='denguecase',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='denguecase',
            old_name='neighborhood',
            new_name='Neighborhood',
        ),
        migrations.RenameField(
            model_name='denguecase',
            old_name='notification_date',
            new_name='NotificationDate',
        ),
        migrations.AddField(
            model_name='denguecase',
            name='Commune',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denguecase',
            name='OccurrenceMonth',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
