# Generated by Django 3.1.2 on 2020-10-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20201020_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DengueCase',
        ),
    ]
