# Generated by Django 3.1.2 on 2020-10-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0003_delete_denguecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DengueCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=50)),
                ('OccurrenceMonth', models.CharField(max_length=20)),
                ('NotificationDate', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Neighborhood', models.CharField(max_length=50)),
                ('Commune', models.CharField(max_length=10)),
            ],
        ),
    ]
