# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_denguecase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DengueCase',
        ),
    ]
